/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Form_MenuUtama extends javax.swing.JFrame {


    /**
     * Creates new form Form_MenuUtama
     */
    public Form_MenuUtama() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_statusair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_nohp = new javax.swing.JLabel();
        jLabel_id = new javax.swing.JLabel();
        jLabel_nama = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_caridata = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_input = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_nohp = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btn_statusair.setBackground(new java.awt.Color(48, 179, 235));
        btn_statusair.setFont(new java.awt.Font("Roboto", 0, 26)); // NOI18N
        btn_statusair.setText("Status Air : Tersedia");
        jPanel1.add(btn_statusair);
        btn_statusair.setBounds(374, 144, 287, 80);

        jPanel2.setPreferredSize(new java.awt.Dimension(1440, 115));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU UTAMA");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(452, 20, 679, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1478, 115);

        jPanel3.setBackground(new java.awt.Color(48, 179, 235));
        jPanel3.setLayout(null);

        jLabel_nohp.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_nohp.setText("NO HP :");
        jPanel3.add(jLabel_nohp);
        jLabel_nohp.setBounds(30, 230, 101, 45);

        jLabel_id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_id.setText("ID :");
        jPanel3.add(jLabel_id);
        jLabel_id.setBounds(30, 130, 101, 45);

        jLabel_nama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_nama.setText("NAMA :");
        jPanel3.add(jLabel_nama);
        jLabel_nama.setBounds(30, 180, 101, 45);

        btn_logout.setBackground(new java.awt.Color(227, 247, 255));
        btn_logout.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_logout.setText("LOGOUT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel3.add(btn_logout);
        btn_logout.setBounds(50, 830, 262, 96);

        btn_caridata.setBackground(new java.awt.Color(227, 247, 255));
        btn_caridata.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_caridata.setText("CARI DATA");
        btn_caridata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_caridataActionPerformed(evt);
            }
        });
        jPanel3.add(btn_caridata);
        btn_caridata.setBounds(50, 310, 262, 96);

        btn_laporan.setBackground(new java.awt.Color(227, 247, 255));
        btn_laporan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_laporan.setText("LAPORAN");
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });
        jPanel3.add(btn_laporan);
        btn_laporan.setBounds(50, 570, 262, 96);

        btn_refresh.setBackground(new java.awt.Color(227, 247, 255));
        btn_refresh.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_refresh.setText("REFRESH");
        jPanel3.add(btn_refresh);
        btn_refresh.setBounds(50, 700, 262, 96);

        btn_input.setBackground(new java.awt.Color(227, 247, 255));
        btn_input.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_input.setText("INPUT");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });
        jPanel3.add(btn_input);
        btn_input.setBounds(50, 440, 262, 96);

        txt_id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel3.add(txt_id);
        txt_id.setBounds(160, 130, 180, 45);

        txt_nama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel3.add(txt_nama);
        txt_nama.setBounds(160, 180, 180, 45);

        txt_nohp.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel3.add(txt_nohp);
        txt_nohp.setBounds(160, 230, 180, 45);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 2, 359, 1020);

        jPanel4.setMinimumSize(new java.awt.Dimension(893, 861));
        jPanel4.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GALON.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(893, 163));
        jLabel2.setRequestFocusEnabled(false);
        jLabel2.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLabel2);
        jLabel2.setBounds(0, 0, 893, 861);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(431, 163, 893, 861);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        int pesan=JOptionPane.showConfirmDialog(null, "Yakin Ingin Keluar?","",JOptionPane.YES_NO_OPTION
            ,JOptionPane.QUESTION_MESSAGE);
        if(pesan==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_caridataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_caridataActionPerformed
        // TODO add your handling code here:
        new Form_Caridata().show();
    }//GEN-LAST:event_btn_caridataActionPerformed

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        // TODO add your handling code here:
        new Form_Input().show();
    }//GEN-LAST:event_btn_inputActionPerformed

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        // TODO add your handling code here:
        new Form_Laporan().show();
    }//GEN-LAST:event_btn_laporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_caridata;
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_statusair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_nama;
    private javax.swing.JLabel jLabel_nohp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nohp;
    // End of variables declaration//GEN-END:variables
}
