/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author USER
 */
public class Form_Caridata extends javax.swing.JFrame {


    /**
     * Creates new form Form_MenuUtama
     */
    public Form_Caridata() {
        initComponents();
        panel_bground2.setBackground(new Color(27,22,22,127));
        paneljudul_table.setBackground(new Color(0,204,255,204));
        table.setBackground(new Color(255,255,255,0));
        table.setDefaultRenderer(Object.class, new table_warna(new Color(0,204,255,229), new Color(0,204,255,178)));
        lebarKolom();
        table.setRowHeight(56);
        
    }
    
    public void lebarKolom(){ 
        TableColumn column;
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = table.getColumnModel().getColumn(0); 
        column.setPreferredWidth(78);
        column = table.getColumnModel().getColumn(1); 
        column.setPreferredWidth(279); 
        column = table.getColumnModel().getColumn(2); 
        column.setPreferredWidth(353); 
        column = table.getColumnModel().getColumn(3); 
        column.setPreferredWidth(326); 
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_judul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_menu = new javax.swing.JPanel();
        jLabel_nohp = new javax.swing.JLabel();
        jLabel_id = new javax.swing.JLabel();
        jLabel_nama = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_caridata = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_input = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_nohp = new javax.swing.JTextField();
        jLabel_idpelanggan = new javax.swing.JLabel();
        txt_idpelanggan = new javax.swing.JTextField();
        btn_batalkan = new javax.swing.JButton();
        btn_kirim = new javax.swing.JButton();
        btn_cari = new javax.swing.JButton();
        table = new javax.swing.JTable();
        judultable_id = new javax.swing.JLabel();
        judultable_nama = new javax.swing.JLabel();
        judultable_tgl = new javax.swing.JLabel();
        paneljudul_table = new javax.swing.JPanel();
        panel_bground2 = new javax.swing.JPanel();
        panel_galon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        panel_judul.setPreferredSize(new java.awt.Dimension(1440, 115));
        panel_judul.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CARI DATA");
        panel_judul.add(jLabel1);
        jLabel1.setBounds(452, 20, 679, 60);

        jPanel1.add(panel_judul);
        panel_judul.setBounds(0, 0, 1478, 115);

        panel_menu.setBackground(new java.awt.Color(48, 179, 235));
        panel_menu.setLayout(null);

        jLabel_nohp.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_nohp.setText("NO HP :");
        panel_menu.add(jLabel_nohp);
        jLabel_nohp.setBounds(30, 230, 101, 45);

        jLabel_id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_id.setText("ID :");
        panel_menu.add(jLabel_id);
        jLabel_id.setBounds(30, 130, 101, 45);

        jLabel_nama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_nama.setText("NAMA :");
        panel_menu.add(jLabel_nama);
        jLabel_nama.setBounds(30, 180, 101, 45);

        btn_logout.setBackground(new java.awt.Color(227, 247, 255));
        btn_logout.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_logout.setText("LOGOUT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        panel_menu.add(btn_logout);
        btn_logout.setBounds(50, 830, 262, 96);

        btn_caridata.setBackground(new java.awt.Color(227, 247, 255));
        btn_caridata.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_caridata.setText("CARI DATA");
        panel_menu.add(btn_caridata);
        btn_caridata.setBounds(50, 310, 262, 96);

        btn_laporan.setBackground(new java.awt.Color(227, 247, 255));
        btn_laporan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_laporan.setText("LAPORAN");
        panel_menu.add(btn_laporan);
        btn_laporan.setBounds(50, 570, 262, 96);

        btn_refresh.setBackground(new java.awt.Color(227, 247, 255));
        btn_refresh.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_refresh.setText("REFRESH");
        panel_menu.add(btn_refresh);
        btn_refresh.setBounds(50, 700, 262, 96);

        btn_input.setBackground(new java.awt.Color(227, 247, 255));
        btn_input.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_input.setText("INPUT");
        btn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputActionPerformed(evt);
            }
        });
        panel_menu.add(btn_input);
        btn_input.setBounds(50, 440, 262, 96);

        txt_id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panel_menu.add(txt_id);
        txt_id.setBounds(160, 130, 180, 45);

        txt_nama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panel_menu.add(txt_nama);
        txt_nama.setBounds(160, 180, 180, 45);

        txt_nohp.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        panel_menu.add(txt_nohp);
        txt_nohp.setBounds(160, 230, 180, 45);

        jPanel1.add(panel_menu);
        panel_menu.setBounds(0, 2, 359, 1020);

        jLabel_idpelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel_idpelanggan.setText("ID PELANGGAN :");
        jPanel1.add(jLabel_idpelanggan);
        jLabel_idpelanggan.setBounds(391, 212, 228, 47);

        txt_idpelanggan.setBackground(new java.awt.Color(196, 196, 196));
        txt_idpelanggan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jPanel1.add(txt_idpelanggan);
        txt_idpelanggan.setBounds(651, 216, 377, 45);

        btn_batalkan.setBackground(new java.awt.Color(48, 179, 235));
        btn_batalkan.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_batalkan.setText("DELETE");
        btn_batalkan.setBorder(null);
        btn_batalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalkanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batalkan);
        btn_batalkan.setBounds(852, 874, 262, 96);

        btn_kirim.setBackground(new java.awt.Color(48, 179, 235));
        btn_kirim.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_kirim.setText("EDIT");
        btn_kirim.setBorder(null);
        jPanel1.add(btn_kirim);
        btn_kirim.setBounds(1154, 874, 262, 96);

        btn_cari.setBackground(new java.awt.Color(196, 196, 196));
        btn_cari.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        btn_cari.setText("CARI");
        jPanel1.add(btn_cari);
        btn_cari.setBounds(1060, 216, 135, 45);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "ID Pelanggan", "Nama Pelanggan", "Tanggal Pesanan"
            }
        ));
        table.setGridColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(table);
        table.setBounds(375, 365, 1037, 240);

        judultable_id.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        judultable_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_id.setText("ID Pelanggan");
        jPanel1.add(judultable_id);
        judultable_id.setBounds(455, 293, 278, 57);

        judultable_nama.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        judultable_nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_nama.setText("Nama Pelanggan");
        jPanel1.add(judultable_nama);
        judultable_nama.setBounds(733, 293, 353, 57);

        judultable_tgl.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        judultable_tgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultable_tgl.setText("Tanggal Pesanan");
        jPanel1.add(judultable_tgl);
        judultable_tgl.setBounds(1086, 293, 326, 57);

        paneljudul_table.setLayout(null);
        jPanel1.add(paneljudul_table);
        paneljudul_table.setBounds(375, 293, 1037, 57);

        panel_bground2.setBackground(new java.awt.Color(255, 255, 255));
        panel_bground2.setLayout(null);
        jPanel1.add(panel_bground2);
        panel_bground2.setBounds(358, 113, 1082, 911);

        panel_galon.setMinimumSize(new java.awt.Dimension(893, 861));
        panel_galon.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/GALON.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(893, 163));
        jLabel2.setRequestFocusEnabled(false);
        jLabel2.setVerifyInputWhenFocusTarget(false);
        panel_galon.add(jLabel2);
        jLabel2.setBounds(0, 0, 893, 861);

        jPanel1.add(panel_galon);
        panel_galon.setBounds(431, 163, 893, 861);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputActionPerformed
        // TODO add your handling code here:
        new Form_Input().show();
    }//GEN-LAST:event_btn_inputActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        
        int response = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar ?", "LOGOUT", JOptionPane.YES_NO_OPTION);
            
        if(response == JOptionPane.YES_OPTION){
                    new Form_Login().show();
        }                                          
        else if(response==JOptionPane.NO_OPTION){
            
        }

    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_batalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalkanActionPerformed
        // TODO add your handling code here:
        
        int response = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus ?", "DELETE", JOptionPane.YES_NO_OPTION);
            
        if(response == JOptionPane.YES_OPTION){
            // Isi fungsinya disini ...        
        }                                          
        else if(response==JOptionPane.NO_OPTION){
            // Isi fungsinya disini ...
        }
        
    }//GEN-LAST:event_btn_batalkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Caridata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batalkan;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_caridata;
    private javax.swing.JButton btn_input;
    private javax.swing.JButton btn_kirim;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_idpelanggan;
    private javax.swing.JLabel jLabel_nama;
    private javax.swing.JLabel jLabel_nohp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judultable_id;
    private javax.swing.JLabel judultable_nama;
    private javax.swing.JLabel judultable_tgl;
    private javax.swing.JPanel panel_bground2;
    private javax.swing.JPanel panel_galon;
    private javax.swing.JPanel panel_judul;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel paneljudul_table;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_idpelanggan;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nohp;
    // End of variables declaration//GEN-END:variables
}
